language: node_js

node_js: stable

cache:
    apt: true
    directories:
        - node_modules

before_install:
    - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - hexo clean
  - hexo d -g

after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "anotherten"
  - git config user.email "15086799777@139.com" 
  - git add .
  - git commit -m "Travis CI Auto Builder" 
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master

branches:
  only:
    - master  
env:
 global:
   - GH_REF: github.com/anotherten/anotherten.github.io.git